### ISSUE TITLE
Missing dependency: samtools

### ISSUE THREAD

**Issue by steveandroulakis** [MonashBioinformaticsPlatform/RNAsik-pipe#1]
Your dependencies in the [README](https://github.com/MonashBioinformaticsPlatform/RNAsik-pipe/blob/master/README.md) are listed as:

BigDataScript
STAR aligner
Picard tools
RNA-SeQC
featureCounts

But samtools appears to be required:
`/root/data/run/RNAsik-pipe.20151028_011201_549/task.sikMakeIndices.Indexing_FASTA_file.line_45.id_2.sh: samtools: not found`

Maybe update your docs to make sure all the dependencies are covered? Cheers

**Comment by serine** [comment]
Yes, I forgot to mention that in my docs, samtools are definitely needed. I just update the docs. Thanks for pointing this out.
