### ISSUE TITLE
Installation Instructions Unclear

### ISSUE THREAD

**Issue by andrewyatz** [MonashBioinformaticsPlatform/RNAsik-pipe#15]
Hi there

I am reviewing your JOSS paper submission. I have been trying to run your Ansible playbooks as detailed here https://monashbioinformaticsplatform.github.io/RNAsik-pipe/docs/#installation however the procedure does not work. Running this on my Mac I get the following response:

```sh
$ ansible-playbook -i host bio.yml --tags bds,rnasik,star,bwa,hisat2,subread,samtools,htslib,bedtools,picard,qualimap,fastqc,multiqc
 [WARNING]: Unable to parse /Users/ayates/rnasik/bio-ansible/host as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will
be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see: http://docs.ansible.com/ansible/playbooks_roles.html#task-include-
files-and-encouraging-reuse   for currently supported syntax regarding included files and variables. This feature will be removed in version 2.7. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: Could not match supplied host pattern, ignoring: bio


PLAY [Installing bioinformatics tools] *******************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP ***********************************************************************************************************************************************************************
```

I am running Ansible v2.4.3.0 and updated to this version this morning. Can you please look into this or alter your installation documentation to clarify the requirements to run your playbook.

Thanks

**Comment by serine** [comment]
@andrewyatz sorry about that, it was a typo in the docs, fixed now. It was meant to be `hosts` not `host` file. You should find that file inside `bio-ansible` repository. It is an inventory file that you can specify different remote machines (servers). Idea of ansible is that you could install `RNAsik` (or any other of `bio-ansible` tasks) on multiple machines with one command given that you've put those machine's IP address into inventory file. 
For a purpose of single installation `local` (`localhost`) i.e your current machine is all you need, which is default inside `hosts` file

Give another go now that the docs have been updated

Thanks
