### ISSUE TITLE
Make Python scripts compatible with Python 3.x and 2.7

### ISSUE THREAD

**Issue by pansapiens** [MonashBioinformaticsPlatform/RNAsik-pipe#17]
The current Python scripts are 2.x only but should be ported to be 2.7 and 3.x compatible.

This is causing headaches on HPC where the multiqc module depends on Python 3 - there are various workarounds but the best solution is just to make these scripts 2/3 compatible.

**Comment by serine** [comment]
Yep, this is on the roadmap, aiming for 1.4.11 Q1 (February/March) 2018. More likely end of March

Thanks
