### ISSUE TITLE
Accomodating fastq file names from other sequencers (BGISEQ)

### ISSUE THREAD

**Issue by methylnick** [MonashBioinformaticsPlatform/RNAsik-pipe#19]
It appears with BGI, they have their own result output structure. Which has some implications with RNASik and how it handles such files.

please see this path:
`/mnt/cephfs/scratch/nick.wong/alison.anderson/cdts-wh.genomics.cn/F18FTSAPHT0121_HUMxcaE/Clean`

Differences are, each sample is a folder. Within each folder is the fastq file name which is a different structure than normal Illumina data. 

`CL100059708_L2_WHHUMxcaEAABRAAPEI-543_1.fq.gz`

_1 is the read id
543 is the sample number
the preceding characters are the machine and flowcell it would seem.

**Comment by serine** [comment]
@methylnick sorry taking it a while to get back to you. `RNAsik` should handle this fine. I might have made some improvements in the last couple of month, so best to grab latest version. 

Use these options when running `RNAsik`

`-pairIds "_1,_2" -extn "fq.gz"`

Let me know how it goes

Cheers

**Comment by serine** [comment]
@methylnick going to close this issue as I think it should all work and not actual bug/problem with the code. Feel free to reopen if needed. 

Cheers
