### ISSUE TITLE
Generate *-withNames-proteinCoding.txt counts for each different strandedness option

### ISSUE THREAD

**Issue by pansapiens** [MonashBioinformaticsPlatform/RNAsik-pipe#42]
Since the strandedness guessing isn't always correct, the Degust-compatible `*-withNames-proteinCoding.txt` counts and `*-withNames.txt` counts files should be generated for all three possibilities, irrespective of the stand guessing.

Alternatively, you could only generate all three when the strandedness is unclear (eg in the ranges [0.1, 0.9] or [-0.1, -0.9]) - but to keep it simple, I'd just generate all three every time.

**Comment by serine** [comment]
@pansapiens I think you mean is NOT always correct. Yes sometimes it gets it wrong. I literally just fixed it. hehe. 

However note that while all three pretified count files will be there, multiqc report will still be based off the guess. I should include this into docs. There is no way to fix that without manual check and re-run. Ideally multiqc would display all three metrics as well. We had implemented in our fork, maybe we need to go back to that instead..?
