### ISSUE TITLE
Fatal error: /mnt/software/apps/RNAsik-pipe-1.5.3/bin/../src/sikProcBam.bds, line 21, pos 40. java.lang.Long cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by SpeculativeCynic** [MonashBioinformaticsPlatform/RNAsik-pipe#48]
I'm new to using the RNAsik pipeline. When I try run the following,  

"RNAsik -fqDir /home/bkag0002/scRNAseq/Storer -align star -all -gtfFile /home/bkag0002/scRNAseq/Alberto_Rosello_Diez_scRNA-seq/custom_genome_reference/Annotation/genes_transgenes_custom.gtf -fastaRef /home/bkag0002/scRNAseq/Alberto_Rosello_Diez_scRNA-seq/custom_genome_reference/custom_mm10_transgene/mm10_tdTomato_WPRE.fa -umi"

I get the following output:
"
RNAsik version 1.5.3
00:00:00.278    Warning (/mnt/software/apps/RNAsik-pipe-1.5.3/bin/../src/sikFqFiles.bds, line 272, pos 9): Samples sheet file sikRun/samplesSheet.txt already exists, NOT overwriting it! Rename the file if you want new samples sheet file
Fatal error: /mnt/software/apps/RNAsik-pipe-1.5.3/bin/../src/sikProcBam.bds, line 21, pos 40. java.lang.Long cannot be cast to java.lang.Double

ProgramCounter.pop(100):        Node ID does not match!
        PC         : PC: size 9 / 0, nodes: 1422 -> 28769 -> 28801 -> 28802 -> 20797 -> 20899 -> 20900 -> 20901 -> 20902
        Node Id    : 20904
        bdsNode Id : 20902
ProgramCounter.pop(100):        Node ID does not match!
        PC         : PC: size 8 / 0, nodes: 1422 -> 28769 -> 28801 -> 28802 -> 20797 -> 20899 -> 20900 -> 20901
        Node Id    : 20902
        bdsNode Id : 20901
ProgramCounter.pop(100):        Node ID does not match!
        PC         : PC: size 7 / 0, nodes: 1422 -> 28769 -> 28801 -> 28802 -> 20797 -> 20899 -> 20900
        Node Id    : 20901
        bdsNode Id : 20900
ProgramCounter.pop(100):        Node ID does not match!
        PC         : PC: size 6 / 0, nodes: 1422 -> 28769 -> 28801 -> 28802 -> 20797 -> 20899
        Node Id    : 20900
        bdsNode Id : 20899
ProgramCounter.pop(100):        Node ID does not match!
        PC         : PC: size 5 / 0, nodes: 1422 -> 28769 -> 28801 -> 28802 -> 20797
        Node Id    : 20899
        bdsNode Id : 20797
ProgramCounter.pop(100):        Node ID does not match!
        PC         : PC: size 4 / 0, nodes: 1422 -> 28769 -> 28801 -> 28802
        Node Id    : 20797
        bdsNode Id : 28802
ProgramCounter.pop(100):        Node ID does not match!
        PC         : PC: size 3 / 0, nodes: 1422 -> 28769 -> 28801
        Node Id    : 28802
        bdsNode Id : 28801
ProgramCounter.pop(100):        Node ID does not match!
        PC         : PC: size 2 / 0, nodes: 1422 -> 28769
        Node Id    : 28801
        bdsNode Id : 28769
ProgramCounter.pop(100):        Node ID does not match!
        PC         : PC: size 1 / 0, nodes: 1422
        Node Id    : 28769
        bdsNode Id : 1422"

I have no idea the cause, only that it may be due to my fastq directory.  I apologise if this is a typical beginner mistake, but I've been playing with various approaches for the last three days and can make no headway. The other other error I can raise is certainly related to the fastq directory where it says no valid files may be found, despite the folder only containing .fastq files. 

Thanks in advance for any help you can offer,

Brett

**Comment by pansapiens** [comment]
This is an issue with Java and/or BigDataScript on this particular host (not an RNAsik bug per-se).
I was trying to fix this host on Friday arvo but didn't get to the bottom of it.
I might not get chance to solve this today, so I suggest if you need to get going quickly you just install RNAsik via conda: https://monashbioinformaticsplatform.github.io/RNAsik-pipe/docs/#installation

**Comment by SpeculativeCynic** [comment]
Thanks Andrew, will do :)
